### ISSUE TITLE
Support target encoding other than UTF-8

### ISSUE THREAD

**Issue by zbateson** [zbateson/MailMimeParser#11]
@tivnet suggests making the target encoding support other charsets other than UTF-8.

@tivnet -- could you explain what the use case is?  Sorry my experience with charsets is somewhat limited, in my experience UTF-8 has always been fine for my needs.

Thank you

**Comment by tivnet** [comment]
@zbateson I am maintaining a site that uses a non-UTF encoding in all pages (there are reasons for this). Incoming emails are parsed and then displayed on support pages. So, I am using this code:

```
	$encodingThatThisSiteUses = 'SOMETHING-NOT-UTF';

	$hMailInfo['body'] = '';
	if ( $res = $message->getHtmlStream() ) {
		$hMailInfo['body'] = strip_tags( stream_get_contents( $res ) );
	}

...
	// 1. Need to convert again because the stream filter converts to UTF
	// 2. Not sure if it was converted, or it was a 'pass'? Shall I use 'detect encoding'?
	$hMailInfo['body'] = mb_convert_encoding( $hMailInfo['body'], $encodingThatThisSiteUses, 'UTF-8' );
```

**Comment by zbateson** [comment]
Fair enough.  I guess another use case would be storing the email in a database with a specific charset also.

Looking into charsets for your PR and issue with ISO-8859-8-I, mb_detect_encoding is pretty much useless unfortunately, see this explanation here: http://stackoverflow.com/a/9712883/335059

**Comment by tivnet** [comment]
Yes, of course, all emails go to the DB, which is also not in UTF.

Note about mb detect was kind of sarcastic, sorry :) It is hardly reliable...

**Comment by zbateson** [comment]
Aah, makes sense :smiley:

**Comment by zbateson** [comment]
In 1.0, the target charset of content can be specified, for example:

```php
$message->getContent('UTF-16');
```
In addition, the charset of the stream can also be overridden if known to be something else:

```php
$message->setCharsetOverride('WINDOWS-1252');
echo $message->getContent('ISO-8859-8');
```
Would result in reading the content as WINDOWS-1252, but converting to ISO-8859-8 as a result of the call to getContent.
