### ISSUE TITLE
Images wont appear in Message.

### ISSUE THREAD

**Issue by mstaack** [zbateson/MailMimeParser#13]
Hey again!
i have a Problem with Images that get malformed.

When i use getHtmlStream()

Links and Image Tags appear like this.

```
    <img src=3D"http://g-ec2.images-amazon.com/images/G/01/e-=
mail/logos/a_de_prime_logo_48.gif" alt=3D"Amazon.de" border=3D"0" hspace=3D=
"6" vspace=3D"6">
```

Where does the 3D come from? Something with encoding seems to be broken?

any hints? ideas?

**Comment by mstaack** [comment]
sometimes i get a filter error:
```
stream_get_contents(): stream filter (convert.quoted-printable-decode): invalid byte sequence
```

**Comment by zbateson** [comment]
Hi @mstaack -

Yes, it's probably decoding-related.  "=3D" is quoted-printable for the "=" character... so yes, for whatever reason it's having difficulty decoding that mime part.

Is that the full content of the error message, there's no hint at what character is causing a problem exactly?

Would it be possible to include more of the mime message?  For instance the headers for the HTML part? (perhaps character-encoding is causing an issue)?

**Comment by zbateson** [comment]
Hi @mstaack 

Unfortunately try as I might with the emails you sent me I'm not experiencing any problems parsing them.  I tried all release versions.

What version of PHP are you using, and what environment is it running on?  Are you able to successfully run all the phpunit tests?

```
php /usr/local/bin/phpunit --configuration=tests/phpunit.xml
```

**Comment by mstaack** [comment]
seems to work now. dont know why exactly
