### ISSUE TITLE
setter functions

### ISSUE THREAD

**Issue by postme** [zbateson/MailMimeParser#14]
Hi Zahid,

Right now I'm using your library in my mail processing code, I'm very happy with it and I enjoy using it, thank you for releasing this. 

I would be interested to learn whether you are considering to also implement setter functions? Right now I read the email, parse it with mailmimeparser and then create a new mime object via SwiftMailer API in which I copy/construct elements that I have read/parsed via MailMimeParser. This works but doesn't feel elegant so if there's any inclination on providing setter functions that would be great news for me :-)

Thanks again for your great work and kind regards
Meint

**Comment by zbateson** [comment]
Hi @postme 

I did consider that... I was thinking perhaps the best solution would be to reuse objects from a different library, but in searching I didn't find one that fit my needs exactly unfortunately.

I guess my question is though, if we were to create setter methods, how would the objects provided in MailMimeParser tie into SwiftMailer?  Perhaps the best would be an integration side-project... what do you think of that idea?

Thanks again for the excellent feedback :)

Zaahid

**Comment by postme** [comment]
Thanks for the setter functions!
