### ISSUE TITLE
Attachment saving to specific Directory

### ISSUE THREAD

**Issue by channelriyas** [zbateson/MailMimeParser#15]
Hi zbateson,

I just tried this library everything works well, really appreciating your effort and time!

I would like to know more about attachment handling, in single word how I can save all of attachments to specific directory in my server?
Here I am standing now
`$att = $message->getAttachmentPart(0);   `
`$atts = $message->getAllAttachmentParts();`

Could please help me on this? it will be very helpful, I already spend lot-of time to figure out  :(

Again Thanks for this great library!

**Comment by zbateson** [comment]
Hi @channelriyas 

Sure -- perhaps some extra documentation is needed there :) you should be able to:

```php
$atts = $message->getAllAttachmentParts();
$ind = 0;
foreach ($atts as $part) {
    $filename = $part->getHeaderParameter(
        'Content-Type',
        'name',
        $part->getHeaderParameter(
             'Content-Disposition',
             'filename',
             '__unknown_file_name_' . $ind
        )
    );
    $out = fopen('/path/to/dir/' . $filename, 'w');
    stream_copy_to_stream($part->getContentResourceHandle(), $out);
}
```

I didn't run this, but that's the basic idea.  Let me know if it works out or if some corrections are needed and I'll add it to the usage guide.

**Comment by channelriyas** [comment]
Hi Zaahid, 
Thanks for quick reply!

I just run this code but got error for this line
`$atts = $message->getAllAttachmentParts();`

`PHP Fatal error:  Call to a member function getAllAttachmentParts() on a non-object in /../../`

is this familiar? 

Thanks!

**Comment by zbateson** [comment]
Hi @channelriyas -

That probably means you haven't assigned anything to $message.  If you look at the example on the project's front page you can see how $message is assigned:

```php
// ...
$message = $mailParser->parse($handle);
// ...
```

unless something went wrong in the call to parse().

**Comment by channelriyas** [comment]
Hi Zaahid,

Yes, figure out the issue, my mistake, accidentally $message replaced with body content, thats why error ;)

Anyway now attachments works well, I can move to specific dir as-well, here is my code some one will help.

```
#!/usr/bin/php -q
<?php
require_once 'vendor/autoload.php';
$mailParser = new ZBateson\MailMimeParser\MailMimeParser();

$handle = fopen ("php://stdin", 'r');
$message = $mailParser->parse($handle);         // returns a ZBateson\MailMimeParser\Message
fclose($handle);

$to  = $message->getHeaderValue('to'); 
$from  = $message->getHeaderValue('from');          // user@example.com
$from_name  = $message->getHeader('from')->getPersonName();    // Person Name
$subject  = $message->getHeaderValue('subject');       // The email's subject

$res = $message->getHtmlStream(); // getTextStream
$body_content = stream_get_contents($res);

$atts = $message->getAllAttachmentParts(); //get all attachments
if($atts){
	$ind = 0;
	foreach ($atts as $part) {
	    $filename = $part->getHeaderParameter(
	        'Content-Type',
	        'name',
	        $part->getHeaderParameter(
	             'Content-Disposition',
	             'filename',
	             '__unknown_file_name_' . $ind
	        )
	    );
	    $out = fopen('/path/to/dir/' . $filename, 'w');
	    stream_copy_to_stream($part->getContentResourceHandle(), $out);
	}
}
?>
```

Zaahid, Thank you very much, this is really awesome library!!!!!!!! :+1:

**Comment by zbateson** [comment]
Excellent, happy to hear that Riyas :)

**Comment by WMGS** [comment]
Hello, I am trying to get the script working using the code example from Riyas above but every time I send a email I receive: "Mail delivery failed: returning message to sender" and no error log is written.

Library is installed: zbateson/mail-mime-parser 0.4.9   MIME email message parser

Can you help me?


#!/usr/bin/php -q
<?php
require_once 'vendor/autoload.php';
$mailParser = new ZBateson\MailMimeParser\MailMimeParser();

$handle = fopen ("php://stdin", 'r');
$message = $mailParser->parse($handle);         // returns a ZBateson\MailMimeParser\Message
fclose($handle);

$to  = $message->getHeaderValue('to'); 
$from  = $message->getHeaderValue('from');          // user@example.com
$from_name  = $message->getHeader('from')->getPersonName();    // Person Name
$subject  = $message->getHeaderValue('subject');       // The email's subject

$res = $message->getHtmlStream(); // getTextStream
$body_content = stream_get_contents($res);

$atts = $message->getAllAttachmentParts(); //get all attachments
if($atts){
    $ind = 0;
    foreach ($atts as $part) {
        $filename = $part->getHeaderParameter(
            'Content-Type',
            'name',
            $part->getHeaderParameter(
                 'Content-Disposition',
                 'filename',
                 '__unknown_file_name_' . $ind
            )
        );
        $out = fopen('attachments/' . $filename, 'w');
        stream_copy_to_stream($part->getContentResourceHandle(), $out);
    }
}
?>
