### ISSUE TITLE
Strip previous mail reply contents!

### ISSUE THREAD

**Issue by channelriyas** [zbateson/MailMimeParser#16]
Zaahid,

The only remaining issue while fetching email body, 
```
$res = $message->getTextStream();  
echo stream_get_contents($res);
```
Email body contains previous replied mail contents too, you know how to remove them? just need final mail contents in thread.

Thanks!

**Comment by zbateson** [comment]
Hi @channelriyas 

Unfortunately that's a complicated request and something that would not be covered by MailMimeParser -- each email client sends replies slightly differently.  There's no standard way of including the original messages, and therefore, no great way to extract just the 'reply' in question.

A solution would involve experimenting with many different clients and how they format replies.  Perhaps at some point a supplementary library to this one would be nice but would be a long ways away :) or perhaps there's something out there already...

**Comment by channelriyas** [comment]
Yes Zaahid, you are right, each email client replies in different standard, I think by comparing previous and new we can filter as a limit, not sure how its work. Anyway thanks for your time I will search on this and will post if get a good solution.
