### ISSUE TITLE
image not shown in $message->getHtmlContent();

### ISSUE THREAD

**Issue by ohfang** [zbateson/MailMimeParser#20]
![default](https://cloud.githubusercontent.com/assets/3423189/20057099/7e3e721a-a524-11e6-9ac0-6f05702de8a0.png)

**Comment by ohfang** [comment]
![default](https://cloud.githubusercontent.com/assets/3423189/20057151/e3a45fc0-a524-11e6-9c57-6c5d0e6ed358.png)

**Comment by zbateson** [comment]
Hi @ohfang 

$message->getHtmlContent will only return the raw HTML.  Those <img> tags are part of that raw HTML.

For a browser to display those pictures you'd have to either replace those <img> tag src attributes with inline base64, e.g. <img src="data:image/jpg;base64,/*base64-data-string here*/" /> or set it to a location where you've placed the image attachment (using ``` getAttachmentPart()->getContentResourceHandle() ``` and replace the cid with the attachment part that has a corresponding Content-ID header.

All the best
