### ISSUE TITLE
Bug when Multipart/Alternative is not lowercase.

### ISSUE THREAD

**Issue by RenierZA** [zbateson/MailMimeParser#21]
I came across a message _(X-Mailer: IncrediMail)_ where content types were not in lowercase.  This still works for most parts, but Multipart/Alternative causes `getTextContent()` to fail.

I'm unable to do a pull request currently, but it can be fixed by adding `strtolower()` in [line 121](https://github.com/zbateson/MailMimeParser/blob/master/src/Message.php#L121) of _Message.php_:
```php
private function addToAlternativeContentPartFromParsed(MimePart $part)
{
    $partType = strtolower($this->contentPart->getHeaderValue('Content-Type'));
```

**Comment by zbateson** [comment]
Excellent, thanks @RenierZA 

Fixed in master and will be released in 0.3.2 early December.
