### ISSUE TITLE
application/tnef messages are not handled correctly

### ISSUE THREAD

**Issue by postme** [zbateson/MailMimeParser#24]
[application-ms-tnef.txt](https://github.com/zbateson/MailMimeParser/files/651758/application-ms-tnef.txt)

Error: Fatal error: Call to a member function getParent() on null in /var/task/vendor/zbateson/mail-mime-parser/src/Message.php on line 477

**Comment by zbateson** [comment]
Hi Meint,

Fixed in the just released 0.3.2 :) please reopen/let me know if you have any issues.

**Comment by postme** [comment]
Thank you Zaahid, fix works correct.
