### ISSUE TITLE
multipart/digest not handled correctly

### ISSUE THREAD

**Issue by postme** [zbateson/MailMimeParser#25]
Fatal error: Call to a member function getParent() on null in /var/task/vendor/zbateson/mail-mime-parser/src/Message.php on line 477

[multipart-digest.txt](https://github.com/zbateson/MailMimeParser/files/651783/multipart-digest.txt)

**Comment by zbateson** [comment]
Hi Meint,

Fixed in the just released 0.3.2 :) please reopen/let me know if you have any issues.

**Comment by postme** [comment]
Hi Zaahid, fix works correctly, thank you!
