### ISSUE TITLE
Error in base64 decoding

### ISSUE THREAD

**Issue by vvv476** [zbateson/MailMimeParser#26]
Sometimes happen decoding error attachments. 
Problem ($this->leftover = '0') is here: Base64DecodeStreamFilter.php
        if (!empty($this->leftover)) {
Fix:
        if (strlen($this->leftover)) {

**Comment by zbateson** [comment]
Nice -- thank you for pointing that out :+1: 

My terrible use of "empty" in a number of places has been fixed on master.

All the best!
