### ISSUE TITLE
Apple Mail html part not recognized by getHtmlPart() / getHtmlStream()

### ISSUE THREAD

**Issue by postme** [zbateson/MailMimeParser#29]
Apple Mail creates a very complex, nested structure for HTML e-mail that MailMimeParser is not able to recognize correctly. Example sent as attachment directly.

**Comment by zbateson** [comment]
Hi @postme --

This one's a bit of a funny one, the 'html' alternative part actually has multiple HTML parts within it in the example you sent (the signature is in the second, and there are some empty ones after).  I've fixed this by returning the first one by default, and by allowing you to get at multiple parts if they exist as well in the latest version.

``` $message->getHtmlPart() ``` would return the first one if multiple parts exist.

``` $message->getAllPartsByMimeType('text/html'); ``` returns an array, and could have more than one.

I hope this helps.  I've improved the writing process quite a bit as well, so please give it some testing if you can also and let me know how it goes.

All the best!

**Comment by postme** [comment]
Hi Zaahid, the modifications work as advertised, thank you!
However a new issue pops up, as as soon as I apply removeTextPart() to the message all MIME parts are removed, including any attachments. I've created a specific anonymized test case and added it to this message.

[apple-mail-test.zip](https://github.com/zbateson/MailMimeParser/files/766090/apple-mail-test.zip)

Apple for sure are the Microsoft of this decade, why on earth is Apple Mail adding multiple html or text bodies to a message? It just blows my mind anybody would contemplate such a silliness.

**Comment by postme** [comment]
BTW Apple Mail madness ensues with another example of multiple bodies, this time for text/plain. I know the standard allows multiple bodies but I'm stumped why anybody would want to do this.

[[54]-apple-mail-multiple-text-bodies.zip](https://github.com/zbateson/MailMimeParser/files/784852/54.-apple-mail-multiple-text-bodies.zip)

I think your approach with getAllPartsByMimeType() is the right course of action. The trick is the removal of certain Mime Parts within the message. Maybe a crude but effective way could be to remove the text part by using the ordering in the list created by getAllPartsByMimeType()? i.e. removeHtmlPart(0) removes the first text/html part from the total list of available text/html parts? If you want to remove them all then iterate through all the available text/html parts and call removeHtmlPart($iter)?

**Comment by zbateson** [comment]
Hmmmm... thanks @postme I'll have a think over next week when I'm back but that sounds pretty reasonable to me.  Might be worth having a removelByMimeType too?

**Comment by zbateson** [comment]
Whoop should say removeAllByMimeType

**Comment by zbateson** [comment]
Hi @postme 

I've released another imperfect update to address this.  I've tested with removeTextPart and removeHtmlPart and added some relevant test code.  Currently if one of the alternative parts is a multipart, it considers it either an HTML or a text part... meaning if there are multiple HTML parts and attachments included in a mixed or "related" multipart, the entire block is removed.

Hopefully this is good enough for now.  The code for this part needs some cleanup to better handle it so I can create removeHtmlPart(0), etc...

Hope it helps :) if it misses something important for you now let me know.  Otherwise I'm working on a much cleaner v1.0 to address a lot of this stuff.

All the best,
Zaahid

**Comment by zbateson** [comment]
Hi @postme -

I've just release 0.4.2 which will hopefully do this issue justice.

In addition to having the removeHtmlPart/removeTextPart with an optional index to remove a specific one, there is now removeAllTextParts, removeAllHtmlParts.  The removeAll* functions will try to remove all inline content parts of that type, and optionally remove any associated inlined parts that are common to an alternative part... consider:

```
multipart/alternative message
 --- text/plain part
 --- multipart/related part
      --- text/html part
      --- image/png part (with Content-Disposition: inline)
```

Passing true to removeAllHtmlParts would result in a text/plain message, and all other parts removed.

The default behaviour moves the image/png part to be on the message, so the message becomes a multipart/mixed message with a text/plain part and an inline image/png part.

Hopefully this finally addresses everything related to these types of messages :)

Please let me know if you notice anything else!

Thanks,
Zaahid

**Comment by postme** [comment]
Works as advertised, thanks Zaahid!
Order seems to be of some importance, i.,e. first do $message->removeTextPart() before $message->removeAllHtmlParts(true); for the desired result.
