### ISSUE TITLE
Message-ID

### ISSUE THREAD

**Issue by insuranceshop** [zbateson/MailMimeParser#33]
Hi, 

Thank you very much for developing the MailMimeParser. So far it is doing exactly what I need it to do, however, having difficulty figuring out how to parse MESSAGE-ID from eml file.

**Comment by zbateson** [comment]
Hi @insuranceshop thanks for the feedback :)

My understanding of Message-ID is it's just an ID identifying a thread of emails as related, so wouldn't $message->getHeaderValue be enough to read it?

Otherwise please elaborate on what it is you're trying to extract from Message-ID :)

All the best

**Comment by postme** [comment]
Yes, can confirm, I'm using the following to get the Message-ID and it works fine:

`$messageId = $message->getHeaderValue('message-id');`

**Comment by insuranceshop** [comment]
Thank you so much, it works! My bad. Thanks for shedding light.
