### ISSUE TITLE
Retrieve all attachments from any header

### ISSUE THREAD

**Issue by xserrat** [zbateson/MailMimeParser#34]
Hi,

I'm wondering if it could be possible to add a feature to retrieve all attachments from any header. I have some emails with the attachment at the `inline` header instead of `attachment`.

However, I've updated to the last version `0.4.0` to try to fix it using the new method `MimePart::getAllPartsByMimeType()` but it doesn't retrieve nothing...

Is there any way to solve this problem? 

I'll try to parsing all ways to send me an attachment in order to fix it...

Thank you so much for this repository :)

**Comment by zbateson** [comment]
Hi @xserrat --

That sounds more like a bug to me.  MailMimeParser should add all parts, whether inline or not, as attachments in the message if the part is not a text/plain, text/html or multipart/* part.

For text/plain and text/html, the part is still added as an attachment if either "inline" or "attachment" are defined in the Content-Disposition header at the moment (although that may be incorrect functionality.)

Would you be able to attach an example of an email where this is happening, or better describe the email?  E.g., it's a multipart/mixed email with one text part, and one attachment part.  The attachment part is an application/pdf has the following headers defined "...".  If I'm not able to reproduce it with the description provided I may ask for additional details.

Thanks for the feedback as well much appreciated :smile:

**Comment by xserrat** [comment]
Thank you @zbateson for your quick reply :)

The email I mentioned doesn't have a visible body. This body is placed at the following header: 

```
--=_the_hash
Content-Type: text/html; charset=iso-8859-1
Content-Transfer-Encoding: quoted-printable
Content-Disposition: inline

MESSAGE CONTENT HERE

--=_the_hash
```

So, if I want to retrieve the content I need to check if `ZBateson\MailMimeParser::getTextContent()` or `ZBateson\MailMimeParser::getHtmlContent()` have content inside. If not, check if an attachment with `Content-Disposition: inline` exists and then, check if `Content-Type` is `text/html`. In this case, we can retrieve the content inside in order to obtain the message content but we need to check some possibilities.

This email has a PDF attachment using the same `Content-Disposition` than the other one:

```
--=_another_hash
Content-Type: application/pdf
Content-Transfer-Encoding: base64
Content-Disposition: inline; filename="the_file_name.pdf"

PDF in BASE64

--=_another_hash
```

Thanks again!

**Comment by zbateson** [comment]
Hi @xserrat 

Technically speaking from reading https://www.ietf.org/rfc/rfc2183.txt which defines the Content-Disposition header, the main part of a message could have a Content-Disposition header, and in its absence either can be chosen.

> "Content-Disposition is an optional header field. In its absence, the MUA may use whatever presentation method it deems suitable."

I'm not sure what makes the most sense for us at this point.  I guess a message defined with an "inline" text/html or text/plain content type, could indeed be the main content of a message.

I'm working on an update to how the text part and html parts are determined also to address another issue where a message may have more than one content-part.  I will also consider "inline" text parts to be part of the message unless others comment against that idea here :)

Unfortunately not mentioned in the documentation is that getAllPartsByMimeType only considers parts without a defined "Content-Disposition" as well.  In the meantime, the only way to get to it would be to loop over ``` getAllAttachmentParts ``` as you're doing.

**Comment by xserrat** [comment]
Perfect @zbateson , thank you so much for you reply 👍

**Comment by zbateson** [comment]
Hi @xserrat -

The latest release specifically addresses this and other issues.  Message::getHtmlPart, getHtmlContent, getTextPart, getTextContent consider inline parts as main content parts.  They all accept integer indexes for messages that contain multiple inline parts as well (defaulting to 0).  The full release notes are here: https://github.com/zbateson/MailMimeParser/releases/tag/0.4.2

This should address the issue you were experiencing without having to work around it.  Please create a ticket if you notice any issues (or reopen this one if it's related!) :smile: 

All the best

**Comment by xserrat** [comment]
Hi @zbateson ,

Thank you again. That's very nice. I'll see this new release and I'll tell you if something goes wrong or something about that 👍 

Cheers!
