### ISSUE TITLE
Parse incorrect  when charset contains shift_jis

### ISSUE THREAD

**Issue by alu** [zbateson/MailMimeParser#36]
Mail headers contain `shift_jis` charset sometime such as below. 

```
Subject: =?shift_jis?B?g1qDfoNJgVuDX4FbirSKb4LFkUmC1IFBg1eDg4NQg2KDZw==?=
 =?shift_jis?B?gUWDcIOTg2OBRYNYg0qBW4NngqqTb4/qgV6BdYKrgr+C8YLGgXaCxg==?=
 =?shift_jis?B?gXWDiYNOg2CDk4F2gvCBQo90gsySyovOlZ6CyYKogreCt4Lfg0GDQw==?=
 =?shift_jis?B?g2WDgA==?=
```

The charset is registered in IANA so conforming to RFC-2047.

I guess that it will solve by adding '_` to [this regex pattern](https://github.com/zbateson/MailMimeParser/blob/master/src/Header/Part/MimeLiteralPart.php#L22).

Thanks.

**Comment by zbateson** [comment]
Hi @alu 

Thanks for letting me know -- I've fixed it in master and will include it in the next release :)

Zaahid

**Comment by alu** [comment]
@zbateson thanks :)
