### ISSUE TITLE
functions countTextParts and countHtmlParts appear to be missing

### ISSUE THREAD

**Issue by postme** [zbateson/MailMimeParser#39]
not a biggie but the release notes for 0.4.2 mention functions countTextParts and countHtmlParts, however these are not available in this version of the library.

Kind regards
Meint

**Comment by zbateson** [comment]
Hahaha, sorry -- I was probably half asleep when I wrote that.  I've updated the release notes, the correct function names are ``` getTextPartCount ``` and ``` getHtmlPartCount ```

Thanks,
Zaahid
