### ISSUE TITLE
Can't get body from simplest email

### ISSUE THREAD

**Issue by postme** [zbateson/MailMimeParser#40]
Hi Zaahid,

I have another Apple case for you :-) (well its actually a bit more generic but this testcase is generated by Mail on iPad)

```
Date: Fri, 10 Jul 2016 15:29:52 GMT
From: "Test Sender" <sender@email.test>
To: "Test Recipient" <recipient@email.test>
Message-ID: <rf51l8iqh6ej4vxsdhkdl0r4bowenl2f@email.test>
Subject: [36]-text-plain-ipad
MIME-Version: 1.0
X-Mailer: iPad Mail (12H143)

Test
```

The body isn't recognized by any of the existing functions (getTextPart, getHtmlPart, getTextStream, getHtmlStream, getTextContent and getHtmlContent), I'm assuming this happens because of the lack of content-type for this simplest of email message formats?

However the message is a valid message.

The only function that triggers is getAllParts() but that just reflects the entire message, including headers.

Kind regards
Meint

**Comment by mstaack** [comment]
@postme can you add a failing test for your message?

**Comment by postme** [comment]
@zbateson What do you mean exactly with a failing test?

**Comment by postme** [comment]
Adding content-type: text/plain to the header resolves the issue, so it looks like getTextContent() gets thrown ofcourse if there's  an email with a text/plain body but without a content-type declaration in the header.

`Date: Fri, 10 Jul 2016 15:29:52 GMT
From: "Test Sender" <sender@email.test>
To: "Test Recipient" <recipient@email.test>
Message-ID: <rf51l8iqh6ej4vxsdhkdl0r4bowenl2f@email.test>
Subject: [36]-text-plain-ipad
MIME-Version: 1.0
X-Mailer: iPad Mail (12H143)
Content-Type: text/plain

Test
`
No problems with this version.

**Comment by zbateson** [comment]
Hi @postme,

The failling test question was from @mstaack :) loving the involvement!

Unfortunately because of this I'm going to announce 0.4.2 as dead.  My new PartFilter class didn't account for header defaults, and I'm rushing in a fix now and looking at how best to resolve it with versioning/composer.

Thanks,
Zaahid

**Comment by zbateson** [comment]
Hi @postme --

I've release 0.4.3 for this.

Thanks,
Zaahid

**Comment by postme** [comment]
Ok everythings back to usual, the testcase is parsing as usual and applemail testcase for multiple html bodies is failing as expected.

**Comment by zbateson** [comment]
:cry: it shouldn't fail though I even have test cases that should match what you're trying to do...

I still have the apple mail in question, but can you share the calls you're making to remove the html parts and tell me how it's failing (again)?

So sorry this one's dragging on so long for you!

**Comment by postme** [comment]
Nope, this turned out to be completely my fault, I had a shameful bug, I fixed it and all testcases now run without issue, yay!

**Comment by zbateson** [comment]
Aaah, I'm so happy to hear that :smile:
