### ISSUE TITLE
get raw email without attachments

### ISSUE THREAD

**Issue by jcbenton** [zbateson/MailMimeParser#41]
First, thanks for writing the library. Highly useful without having to install mailparse. 

I do have a question regarding a feature if it is available. Is there an option to return the raw email (headers + body) with the MIME parts in tact but without attachments? I am looking at feeding this to a spam filter without attachments. If I build a test message using the included features, spamassassin is very unhappy about it missing the MIME boundaries.

**Comment by zbateson** [comment]
Hi @jcbenton --

My pleasure, happy to see it being used :)

The easiest way I can think of would be to remove all attachments and write the message out.

```php
foreach ($message->getAllAttachmentParts() as $part) {
    $message->removePart($part);
}
$msgForSpamFilter = $message->__toString();
```

**Comment by jcbenton** [comment]
Works great. Ran into another issue. Going to check the closed issues before I post anything.
