### ISSUE TITLE
Parsing is incorrect when the last character is '"' оr ')' and is on a new line

### ISSUE THREAD

**Issue by vvv476** [zbateson/MailMimeParser#45]
Example:
Subject: =?koi8-r?B?9MXIzsnexdPLycUg0sHCz9TZIChFUlAg58HMwcvUycvBIMkg79TexdTZIPTk?=
 =?koi8-r?Q?)?=

Problem in splitRawValue function :
Input Parameter: (=?koi8-r?B?9MXIzsnexdPLycUg0sHCz9TZIChFUlAg58HMwcvUycvBIMkg79TexdTZIPTk?=
 =?koi8-r?Q?)?=)
Split Pattern: ~(\\.|\"|\(|\)|\s+)~

Result Array:
(
    [0] => =?koi8-r?B?9MXIzsnexdPLycUg0sHCz9TZIChFUlAg58HMwcvUycvBIMkg79TexdTZIPTk?=
    [1] => 
 
    [2] => =?koi8-r?Q?
    [3] => )
    [4] => ?=
)

I do not know whether it is possible to remove these symbols from the pattern

**Comment by zbateson** [comment]
Hi @vvv476 --

Thanks for the find.  I've fixed the regex to ignore characters inside a mime-encoded part, and hopefully all is well now :smile:

The fix has been released in 0.4.4.

All the best,
Zaahid
