### ISSUE TITLE
Mime - setRawHeader changed header string given

### ISSUE THREAD

**Issue by MagusM** [zbateson/MailMimeParser#49]
Hi I have an issue I would appreciate any help with.

when I set custom header, for example: $mime->setRawHeader("X-HEADER", "value");
it will save it in raw mime as follows: X--HEADER: value . it will add another "-" to header
and it will continue to add a "-" for every run
for example, second run we will see 2 headers:
1. X--HEADER: value
2. X---HEADER: value

and so forth.

the question is why?
and how can i avoid this?

thanks in advance for the help.

**Comment by postme** [comment]
Can you please post the relevant code? I'm adding custom headers myself and this isn't regular behaviour.

**Comment by MagusM** [comment]
thank you
 
the script in short:
 - generate mime from raw mime saved as string in storage
 - generate new ID for internal use saved under X-CLOUD header 
   $mime->setRawHeader("X-CLOUD", {generated id});
   (the generated ID is different value generated with every run of script)
- saves edited mime to back to storage.

the outcome in raw mime is:

...
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="=-ox5zEzpYWcxkXek7zsJa"
X--CLOUD: ^8B2D65CD5F292B44464778A7529DA3610DDF6649

it saves it with double "-" where the header is X-CLOUD with one "-"

if the script is run again, we will see
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="=-ox5zEzpYWcxkXek7zsJa"
X---CLOUD: ^8B2D65CD5F292B44464778A7529DA3610DDF6649



also it modifies 2 other headers that are not being touched in anyway in my script:
X---------Authentication-Warning: mail.mail.com: user set sender to person@mail.com using -f
X---------MAILFROM: person@mail.com

as I can see with every execution of script somehow another "-" is added to the header even when the last 2 headers are not being handled in any way in script


thank you

**Comment by zbateson** [comment]
Hi @MagusM 

Unfortunately I'm not able to reproduce that.

Looking at the tests read/written out in EmailFunctionalTest, there are loads of X-headers being read/written to (for instance /tests/_data/emails/m0001.txt has a few).  I'm not sure any of the tests are actually specifically comparing an X-header, so to be sure I tested m0001.txt, added ```php $content->setRawHeader('X-CLOUD', 'Test'); ``` to ``` testRewriteEmailContentm0001 ``` before writing out the email, and added an additional read for the written email, and wrote the second email out, but no luck.

Could you provide a small example script that actually shows the problem happening?

Thank you,
Zaahid

**Comment by MagusM** [comment]
Hi @zbateson 

here is the code that handles the mime
```
$mime = MailMimeParser\Message::from($str);
$mimeCloudWid = WID\V5Mime::generate($content); //generate a unique ID
$mime->setRawHeader("X-CLOUD", $mimeCloudWid->__toString());
$content = $mime->__toString();
$this->storageConn->upload($content, $mimeCloudWid->getPath()); //uploads to cloud service storage
$widObject->writeFile($content); //save mime back to local storage
```
to fix the addition '-' I have added before $mime->setRawHeader
```
$attachment->removeHeader("X--CLOUD");
```

the 2 other X-headers:
```
X---------Authentication-Warning: mail.mail.com: user set sender to person@mail.com using -f
X---------MAILFROM: person@mail.com
```
been generated in income mails server
and the script do not touch those 2 headers, yet still after I save the edited mime back to storage another '-' is added.

Thank you,
Simon

**Comment by postme** [comment]
What do you see if you dump the string before you upload it?

```
$content = $mime->__toString();
print $content;
$this->storageConn->upload($content, $mimeCloudWid->getPath());
```

**Comment by MagusM** [comment]
Yes ! thank you

mime before script run:
```
Subject: test
To: simontest12345@mail.com
Message-Id: <~002596F33C03776F000286C@mail.com>
MIME-Version: 1.0
X------------------MAILFROM: simontest12345@mail.com
Content-Type: multipart/mixed; boundary="=-U/JYoyIlVB47jh5Qari2"
X-CLOUD: ^8914898E77BD4B7EC398FD085871925BAF4CD50C
```

after 1 script run with only setRawHeader('X-CLOUD' , {generated ID}); 
and **no** removeHeader('X--CLOUD')
```
Subject: sgsdfgsdgs
To: simontest12345@mail.com
Message-Id: <~002596F33C03776F000286C@mail.com>
MIME-Version: 1.0
X-------------------MAILFROM: simontest12345@mail.com
Content-Type: multipart/mixed; boundary="=-U/JYoyIlVB47jh5Qari2"
X--CLOUD: ^8914898E77BD4B7EC398FD085871925BAF4CD50C
X-CLOUD: ^F69C9B60958F4C4A18F4AE1F89CE3891452373ED
```

thank you,

**Comment by postme** [comment]
Looks like there is already an existing X-Cloud header before you apply the setRawHeader? That might explain the behaviour of X--Cloud as a means to preserve the original X-Cloud header? Do you want to keep the original X-Cloud header or do you want to replace this with the new X-Cloud header?

**Comment by MagusM** [comment]
I want to replace the header's value

I use
```
$mime->removeHeader('X--CLOUD');
```
before setting the header again with a new value.

still I was unable to understand why it adds another "-", meaning the header I needed to remove is "X--CLOUD"

that is handled in my script.

the 2 other headers that been changed from reason unknown to me at this point (my script do not handle those 2 headers)
```
X-MAILFROM
and
X-Authentication-Warning
```

thank you

**Comment by MagusM** [comment]
Hi

the problem has been found, and it was on our end.

I'm sorry for the trouble and thank you so much for the help.

**Comment by zbateson** [comment]
Happy to hear it was resolved :)

All the best,
Zaahid
