### ISSUE TITLE
How to get all personnames?

### ISSUE THREAD

**Issue by postme** [zbateson/MailMimeParser#5]
Hi there,
first of all thank you for this library, its really great and I'm having a lot of fun with it! 

I have one functionality that I haven't been able to get fully working which is the getPersonName method in a situation where there are multiple to addresses. I can get a list of all the email to addresses via getHeader('To')->getAddresses() and also via getHeader('To')->getParts() and I can get the first name of the first email address via $message->getHeader('To')->getPersonName(). However how do I get all full names if there is more than one email address?

thanks and kind regards
Meint

**Comment by zbateson** [comment]
Hi @postme

Thanks for the encouragement, very happy to see this being used and appreciated -- so thank you!

So ``` AddressHeader::getAddresses() ``` returns an array of ``` AddressPart ``` objects (including all addresses that may be part of an address group).  AddressPart extends ParameterPart which provides a getName method.  You should be able to:

```php
$addresses = $message->getHeader('To')->getAddresses();
foreach ($addresses as $addr) {
    echo $addr->getName();
}
```

All the best,
Zaahid

**Comment by postme** [comment]
Yep, that was it, thanks for your help! I didn't make the connection with getName, the documentation states:

getName
string ZBateson\MailMimeParser\Header\AbstractHeader::getName()
Returns the name of the header.

Which I interpreted as the MIME header name so I didn't look into that option.

All solved, happy as a clam, thanks again.
