### ISSUE TITLE
If half-width kana is mixed in the character string, it will not be parse.

### ISSUE THREAD

**Issue by sjisjis** [zbateson/MailMimeParser#50]
```
Subject: =?iso-2022-jp?Q?=1B$B300Y=1B(I5]W2]C^S=1B(B(25?=
 =?iso-2022-jp?Q?)(=1B$B%G%b=1B(B)=1B$B7h:QLsDj$N$*CN$i$;=1B(B?=
```

It is not converted by iconv_mime_decode used in [function decodeMime](https://github.com/zbateson/MailMimeParser/blob/master/src/Header/Part/MimeLiteralPart.php#L68). If it is mb_decode_mimeheader, it will be changed correctly.

**Comment by zbateson** [comment]
Hi @sjisjis --

Unfortunately mb_decode_mimeheader isn't the greatest implementation.  I've noticed with quoted-printable encoding it doesn't convert underscores to spaces (like the iconv implementation)... apparently lower-case hex numbers also don't work according to this comment: http://php.net/manual/en/function.mb-decode-mimeheader.php#21843

And if I recall correctly iconv_* has more character sets supported as well.  The solution may be to either build my own converter or select which one to use based on the charset... kind of like I'm doing in  [CharsetConverter](https://github.com/zbateson/MailMimeParser/blob/master/src/Stream/Helper/CharsetConverter.php).

I'll give it some thought :)

Could you post what that subject line should look like as well after conversion so I can build a correct test case for it?

Thanks,
Zaahid

**Comment by sjisjis** [comment]
Hi @zbateson

```
Subject: =?iso-2022-jp?Q?=1B$B300Y=1B(I5]W2]C^S=1B(B(25?=
 =?iso-2022-jp?Q?)(=1B$B%G%b=1B(B)=1B$B7h:QLsDj$N$*CN$i$;=1B(B?=
```
This subject is converted as follows.
```
echo mb_decode_mimeheader('Subject: =?iso-2022-jp?Q?=1B$B300Y=1B(I5]W2]C^S=1B(B(25?=');
Subject: 外為ｵﾝﾗｲﾝﾃﾞﾓ(25
echo mb_decode_mimeheader('=?iso-2022-jp?Q?)(=1B$B%G%b=1B(B)=1B$B7h:QLsDj$N$*CN$i$;=1B(B?=');
)(デモ)決済約定のお知らせ
php > 
```

Thanks.

**Comment by zbateson** [comment]
Hi @sjisjis 

I'm happy to report this is (hopefully) resolved now.  Please feel free to reopen if you have any issues.

All the best.
