### ISSUE TITLE
set default charset?

### ISSUE THREAD

**Issue by siulee88** [zbateson/MailMimeParser#51]
some mails not english, and no charset in the mail header, so cannot detect charset correctly, can I set user default charset for all mails?

I find out this part in "Stream/CharsetStreamFilter.php", can someone teach me how I can change $charset to user define variable?

    public function onCreate()
    {
        $charset = 'ISO-8859-1';
        $to = 'UTF-8';
        if (!empty($this->params['charset'])) {
            $charset = $this->params['charset'];
        }
        if (!empty($this->params['to'])) {
            $to = $this->params['to'];
        }

        $di = SimpleDi::singleton();
        $this->converter = $di->newCharsetConverter($charset, $to);
    }

thx

**Comment by zbateson** [comment]
Hi @siulee88 

The library doesn't have a nice way of setting a default charset in its current form, apart from ISO-8859-1 as you see in that pasted snippet.

You could extend CharsetStreamFilter and register mailmimeparser-encode with the extended class (using stream_filter_register).  You may have to unregister the default one registered by MMP first I'm not sure off-hand.

At some point I may write something to allow a different default (same as for #11 ).  Please feel free to reopen this if you need further clarification or you have trouble getting it to work.

All the best,
Zaahid
