### ISSUE TITLE
Feature request: ability to name digital signature part

### ISSUE THREAD

**Issue by postme** [zbateson/MailMimeParser#52]
Bit of a nice-have, would be neat to be able to name the digital signature mime part, right now its something like "Nameless attachment 00019.dat" which can lead to customer confusion (what is this attachment, is it a virus?).

**Comment by zbateson** [comment]
Hey @postme it's been a while :smile: 

I'm not sure what would be the best solution for this... it seems strange to me that a client supporting signed messages would report the signature part as an attachment like that.  Or maybe it's a client that doesn't support multipart/signed.

Anyway, quick google search didn't give me much to go with, and my concern is changing something may have an undesirable effect on other clients.  I wonder if you could test something like this though and let me know how it works across a few clients:

```php
$part = $message->getSignaturePart();
$part->setRawHeader('Content-Disposition', 'inline; filename=pgp-signature.txt');
```
I worry though that some clients may then show the signature inline with the email, but technically speaking lack of a 'Content-Disposition' header means the part is effectively inline if not specifically defined as such.

You could alternatively try it as 'attachment' though if some clients do show it inline, and see if that helps.

Finally, you could try setting the 'name' parameter on the Content-Type header which is discouraged and frowned upon but may work if setting 'inline' or 'attachment' messes up some clients:

```php
$part = $message->getSignaturePart();
$ct = $part->getHeader('Content-Type')->getRawValue();
$part->setRawHeader('Content-Type', $ct . '; name=pgp-signature.txt');
```

If the only solution that works is this last one, I may leave it out of MMP and recommend users set it like that with setRawHeader.

All the best :)

**Comment by postme** [comment]
Hi Zaahid, apologies for the late reply, all your suggestions worked like a charm. I went with the 3rd option, no 1 showed inline in gmail. Thanks for your help!

**Comment by zbateson** [comment]
No problem at all, glad it worked for you :)

I'll leave it out of the implementation then and recommend using a 'name' parameter on the Content-Type header.
