### ISSUE TITLE
Support RFC2231 header parameters

### ISSUE THREAD

**Issue by zbateson** [zbateson/MailMimeParser#57]
https://tools.ietf.org/html/rfc2231

**Comment by ThomasLandauer** [comment]
Cool, just wanted to file an issue for this :-) What's the status?

**Comment by zbateson** [comment]
Hi @ThomasLandauer,

Working well in 1.0.0 :)

I'm hoping to have that released around Jan 15.  It's working as-is, but I'm separating out "write" code into a "MailMimeWriter" library which isn't complete (so if you're writing you want want it), and moving from php's stream filtering/streamWrapper to Guzzlehttp\Psr7 streams.

**Comment by ThomasLandauer** [comment]
Great, thanks! :-)

**Comment by zbateson** [comment]
I've just released a 1.0-beta that contains this.  Not sure if you have any time to check it out -- if you do and you discover any issues, please open a new issue :smile: 

Thank you!
