### ISSUE TITLE
Duplicate Header Clobbering

### ISSUE THREAD

**Issue by peter-schmandra-yesmail** [zbateson/MailMimeParser#58]
I have emails with duplicate header names. When I call the "getHeader" method on these names it returns the last entry only. It would be desirable if it would return an array in this case.

**Comment by peter-schmandra-yesmail** [comment]
Oh, and thank you very much. This is a fantastic repo.

**Comment by zbateson** [comment]
Released in 1.0-beta.  If you have a chance to look over it and report any issues that would be great :)
