### ISSUE TITLE
addAttachmentPart() on multipart/alternative results in empty multipart

### ISSUE THREAD

**Issue by Josh-G** [zbateson/MailMimeParser#59]
Thanks for this library, it is extremely well-written. I have a slight issue and I'm not clear if I'm using it incorrectly, however:

I have a Message of type multipart/alternative containing two parts, text/html and text/plain. When I call `addAttachmentPart()`, this calls `setMessageAsMixed()` which turns the message into multipart/mixed and adds the multipart/alternative as a child.

This results in a multipart/mixed containing the text/html, text/plain, an empty multipart/alternative and the attachment part.

My question is: should the textPart and htmlPart not be moved to be children of the multipart/mixed?

**Comment by zbateson** [comment]
Hi @Josh-G 

Thanks for the lovely feedback :)

Quick glance and I believe you're right.  That looks like something I've overlooked.  I'll take a closer look and try push out a fix in the coming week or two.

All the best

**Comment by zbateson** [comment]
Released in 0.4.8
