### ISSUE TITLE
Get last message

### ISSUE THREAD

**Issue by yurii-ploskyi-kindgeek** [zbateson/MailMimeParser#62]
Is it possible to get only original message, without reply's, and forwards. 
for example if I have in body : 

some message

On Tue, Mar 6, 2018 at 7:33 PM, Yurii Ploskyi <yurii.ploskyi@gmail.com>
wrote:

> asdfasdfasdf
>
> On Tue, Mar 6, 2018 at 7:33 PM, Yurii Ploskyi <yurii.ploskyi@gmail.com>
> wrote:
>
>> asdfasdfasdf
>>
>> On Tue, Mar 6, 2018 at 7:33 PM, Yurii Ploskyi <yurii.ploskyi@gmail.com>
>> wrote:
>>
>>> asdf
>>>
>>> On Tue, Mar 6, 2018 at 7:32 PM, Yurii Ploskyi <yurii.ploskyi@gmail.com>
>>> wrote:
>>>
>>>> sdfg
>>>>
>>>> On Tue, Mar 6, 2018 at 7:32 PM, <venue@sandbox7fa88b3af93c4130
>>>> 8174561625a2cc98.mailgun.org> wrote:
>>>>
>>>>> Isn't it fun getting mail?!
>>>>> You've got a message in your inbox.
>>>>>
>>>>> "asd..."
>>>>>
>>>>
>>>>
>>>
>>
>
I want parse only "some message".
Tried to find such function, however none of the methods returns such info.
Thanks in advance

**Comment by zbateson** [comment]
Hi @yurii-ploskyi-kindgeek --

Unfortunately there's no standard way of quoting original messages in a 'reply', and each mail client does it differently.

I haven't tried it, but this library seems to be more a long the lines of what you're looking for: https://packagist.org/packages/willdurand/email-reply-parser

All the best,
Zaahid
