### ISSUE TITLE
Laravel Usage

### ISSUE THREAD

**Issue by kobadg** [zbateson/MailMimeParser#67]
Hello, I have used this in my Laravel application, however when I try to use it the way that you specify... it states that it cannot find the class in question... 
`Class 'ZBateson\MailMimeParser\MailMimeParser' not found  `
I used composer to pull it into the site. 

Any help would be greatly appreciated.

**Comment by zbateson** [comment]
Hi @kobadg --

Did you run ```composer update``` as well?

All the best,
Zaahid

**Comment by kobadg** [comment]
Definitely was the issue... (I blame shared hosting.)
(You don't know how much I appreciate this, as the one I wanted to use cannot be used...because of mailparse...)
