### ISSUE TITLE
Error in header parser

### ISSUE THREAD

**Issue by postme** [zbateson/MailMimeParser#69]
Hi Zaahid,
Hope you're doing well!

I found an issue in the header parser (I think) with certain subject values. It appears to be filtering out certain characters and anything that is caught in between. It's dropping text between () in a subject line but I suspect there are other cases as well where it's misbehaving.

A simple testcase:

```
From: "Test Sender" <test@sender.org>
To: "Test Recipient" <test@recipient.org>
Subject: This is a test (really) this is
Date: Wed, 6 Jun 2018 09:47:37 +0000
Message-ID: <01020163d47e9d23-33e47e28-93df-4dff-9575-bc2adbf5c195-000000@eu-west-1.amazonses.com>
MIME-Version: 1.0

Test

```

Using:

`$message->getHeaderValue('subject');`

Will yield:

`This is a test this is`

I'm using the subject as part of a hashing operation so you can imagine I've been hunting around what was causing the hashing discrepancies :-)

Hope you're able to have a look as its causing quite a bit of manual work on my side to correct the values.

Kind regards and all the best
Meint

**Comment by postme** [comment]
My bad, I didn't check my composer.json and used an old version of the library where this issue existed, switched to last version and the problem is resolved.

**Comment by zbateson** [comment]
Hi @postme 

Sorry for not getting back to you earlier (greetings from Colombia!)

Yes, that was an issue I noticed in an older version.  I was treating text inside parentheses as comments, which applies to most other header values but shouldn't apply to the Subject header.  Anyways, glad you figured it out.

Zaahid
