### ISSUE TITLE
File attaching not working

### ISSUE THREAD

**Issue by miknazarenko** [zbateson/MailMimeParser#70]
```
        $mail = \ZBateson\MailMimeParser\Message::from('');
        $mail->setRawHeader('Subject', 'HELLO');

        $mail->addAttachmentPartFromFile(realpath("a.txt"), mime_content_type(realpath("a.txt")), "HI");

        $commander->append((string) $mail);
```

this code build new message and append it to inbox folder. But file doesn't attached. In the mail body I get "begin 666 HI #:&5Y' end"

How do I attach file properly ? That I can see it in my mail when append ? I am sure, my append method works properly, because I tried fetch message with attachments, parse it to object with your parse method, then convert back to string and append to inbox, attachments appears properly.

**Comment by mvnaz** [comment]
Thank you for your answer! I like your package and I wanted to use it in my package. It's pitty that it not good way in my case ( Can you advice me please some another one for my goal ?

**Comment by zbateson** [comment]
For creating and sending messages I've usually used Swift Mailer and found it to be pretty good.  I've never had a need to just store messages after creating them or do anything else with them, so can't say for sure without digging if it allows to just save a message for instance if that's your need.  I would assume it would though :)

**Comment by mvnaz** [comment]
ok, thank you for your time. I think you can delete this issues because it is not an issue )

**Comment by mvnaz** [comment]
Man thank you ! Swift it's what I need ) Of course I heard about this and used it, but in this case don't remembered that it migh be useful )

**Comment by mvnaz** [comment]
But do you know can I parse mail string by Swift like your package ?

**Comment by zbateson** [comment]
No, you can't parse messages with Swift  Mailer last I checked.  Only
create and send :)

**Comment by mvnaz** [comment]
But is your package good for parsing emails ? I need mainly subject, htmlBody, textBody, date, and files. For now honestly I don't figured out how get the files. Will it work stable for my case ?

**Comment by zbateson** [comment]
Yeah it's very good for parsing and extracting attachments. Modifications
to an email are good too, just not much done for you in that front at this
point.

**Comment by mvnaz** [comment]
Sorry for my impudence, can you please provide me a little code how can I get files from email ?)

**Comment by zbateson** [comment]
No problem at all there are some examples and documentation here:
https://github.com/zbateson/MailMimeParser/wiki/Usage-Guide

Hope it's enough!

**Comment by mvnaz** [comment]
thank you a lot man !
