### ISSUE TITLE
Incorrect quoted-printable parsing in attachement

### ISSUE THREAD

**Issue by janci007** [zbateson/MailMimeParser#72]
If I parse simple email message with one attachement that is long enough and has mixed line lengths in quoted-printable encoding, the output contains stray line endings.

Example message - see attachement,
[long att.eml](https://github.com/zbateson/MailMimeParser/files/2170088/long.att.eml.txt)
Example code - below

```
  $msg = file_get_contents("php://stdin");
  $mailParser = new \ZBateson\MailMimeParser\MailMimeParser();
  $message = $mailParser->parse($msg);
  $att = $message->getAttachmentPart(0);
  $attStr = stream_get_contents($att->getContentResourceHandle());
  echo $attStr;
```

Expected output: file with one line ending at the end of file
Output: there is stray newline betweeen the "aaa" and "xxx" section - see attachement
[out.txt](https://github.com/zbateson/MailMimeParser/files/2170087/out.txt)

**Comment by zbateson** [comment]
Thanks for the report, this is fixed in 0.4.10 :+1:
