### ISSUE TITLE
The email does not keep HTML formatting

### ISSUE THREAD

**Issue by kobadg** [zbateson/MailMimeParser#73]
I use this awesome extension to do a piping for a person-to-person, username@site_domain.com tool... Which it works GREAT, however it seems that the HTML parsing gets stripped out, upon sending back to the server... 

So.. my flow..

Initial Email Sent -> Received | Has HTML email -> Replied -> Replied email parsed and sent -> Recieved | Does not have HTML, and is just a text email.

Could I be missing something key to making this happen?

**Comment by kobadg** [comment]
I use `$message_body = $parser->getMessageBody('text');` when getting the email in, and then pass that variable directly to an array which then sends on to the mail function... (Laravel Mailer, if that makes any difference.)

**Comment by zbateson** [comment]
Hi @kobadg --

Unfortunately your code confuses me.  If Parser is an alias of MailMimeParser, there is no "setStream" function in its api: [MailMimeParser class api](https://github.com/zbateson/MailMimeParser/wiki/ZBateson-MailMimeParser-MailMimeParser)

Also, the way MMP is used, would be more like this:

```
$parser = new \ZBateson\MailMimeParser\MailMimeParser();
$handle = fopen("php://stdin", "r");
$message = $parser->parse($handle);
```

You could then get the HTML message by calling:

```
$message->getHtmlPart()
```

There is no $message->getMessageBody method (or $parser->getMessageBody) defined.

All the best!

**Comment by kobadg** [comment]
Sorry.... my bad, that was old code...

So, the following is actually how I'm using it...Please see the indented section with code comment... maybe that will be the reasoning?

```
$parser = new \ZBateson\MailMimeParser\MailMimeParser();
$fd = fopen("php://stdin", "r");
$message = $parser->parse($fd);
fclose($fd);

$to = $message->getHeaderValue('to');
$from = $message->getHeaderValue('from');
$subject = $message->getHeaderValue('subject');

        //HERE seems to be where the problem is... 
        //Is it because I'm using getHTMLContent() instead of getHTMLPart()???
        $message_body = strip_tags(preg_replace("#<img[^>]*>#i", "",$message->getHtmlContent()), "<p><blockquote><br><h1><h2><h3><h4><h5><h6>");


$new_recipient = User::where('username', str_replace('@domain.com', '', $to))->firstOrFail();
$new_sender = User::where('email', $from)->firstOrFail();

$data = [
    'user' => $new_sender->username,
    'subject' => $subject,
    'message_body' => $message_body
];

Mail::to($new_recipient->email, $new_recipient->username)
              ->send(new SearchNotification($data));
return true;
```

**Comment by zbateson** [comment]
Hi @kobadg -- no, getHtmlContent does as you seem to expect.

Perhaps the message isn't formatted well, and preg_replace or strip_tags is removing more than you expect.  Try setting $message_body to $message->getHtmlContent() directly and write it out to a temp file (or echo to terminal if you can run the code directly), then add each call to see what's going on.

**Comment by kobadg** [comment]
So, just got to being able to fiddle with this... Sorry for the delay..

$message->getHtmlContent() indeed gets me the HTML content... However issue I have is that the HTML get parsed as a string when setting the message again. (Almost like it's seeing the message as a text message, and not an HTML message?)

**Comment by zbateson** [comment]
Hi @kobadg 

Sorry I'm not sure what you mean by "the HTML get parsed as a string when setting the message again".  If the HTML is as-expected in $message->getHtmlContent(), perhaps your strip_tags or preg_replace are still messing you up.
